#!/bin/sh

# Some commonly useful addtional options that can be specified via the
# command line:
#
# --dry-run
# --progress
#
rsync -v -rlpt --copy-unsafe-links \
--prune-empty-dirs --delete-after --delete-excluded $* \
--include '*/'            \
--include '*.tar.gz'      \
--include 'packages'      \
--include 'repositories'  \
--include 'signature'     \
--exclude '*'             \
1/build2.org/ build2.org:/var/pkg/1/
