lib{hello}: {hxx cxx}{hello}

cxx.poptions += -I$src_root
lib{hello}: cxx.export.poptions = -I$src_root

liba{butl}: cxx.export.poptions += -DLIBHELLO_STATIC
libs{butl}: cxx.export.poptions += -DLIBHELLO_SHARED

obja{*}: cxx.poptions += -DLIBHELLO_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBHELLO_SHARED_BUILD

# Install into the hello/ subdirectory of, say, /usr/include/.
#
install.include = $install.include/hello
