// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

#ifndef BPKG_ARGUMENT_GROUPING_HXX
#define BPKG_ARGUMENT_GROUPING_HXX

// Begin prologue.
//
//
// End prologue.

#include <bpkg/common-options.hxx>

// Print page usage information.
//
namespace bpkg
{
  ::bpkg::cli::usage_para
  print_bpkg_argument_grouping_usage (::std::ostream&,
                                      ::bpkg::cli::usage_para = ::bpkg::cli::usage_para::none);
}

// Begin epilogue.
//
//
// End epilogue.

#endif // BPKG_ARGUMENT_GROUPING_HXX
