// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include <bpkg/fetch-cache-data-odb.hxx>

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // pkg_repository_metadata
  //

  struct access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::id_type
  access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::bpkg::repository_url,
          sqlite::id_text >::set_value (
        id,
        i.url_value,
        i.url_size,
        i.url_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // url
    //
    if (t[0UL])
    {
      i.url_value.capacity (i.url_size);
      grew = true;
    }

    // directory
    //
    if (t[1UL])
    {
      i.directory_value.capacity (i.directory_size);
      grew = true;
    }

    // session
    //
    if (t[2UL])
    {
      i.session_value.capacity (i.session_size);
      grew = true;
    }

    // access_time
    //
    t[3UL] = false;

    // repositories_path
    //
    if (t[4UL])
    {
      i.repositories_path_value.capacity (i.repositories_path_size);
      grew = true;
    }

    // repositories_checksum
    //
    if (t[5UL])
    {
      i.repositories_checksum_value.capacity (i.repositories_checksum_size);
      grew = true;
    }

    // packages_path
    //
    if (t[6UL])
    {
      i.packages_path_value.capacity (i.packages_path_size);
      grew = true;
    }

    // packages_checksum
    //
    if (t[7UL])
    {
      i.packages_checksum_value.capacity (i.packages_checksum_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // url
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::image_traits<
        ::bpkg::repository_url,
        sqlite::id_text>::bind_value;
      b[n].buffer = i.url_value.data ();
      b[n].size = &i.url_size;
      b[n].capacity = i.url_value.capacity ();
      b[n].is_null = &i.url_null;
      n++;
    }

    // directory
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.directory_value.data ();
    b[n].size = &i.directory_size;
    b[n].capacity = i.directory_value.capacity ();
    b[n].is_null = &i.directory_null;
    n++;

    // session
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.session_value.data ();
    b[n].size = &i.session_size;
    b[n].capacity = i.session_value.capacity ();
    b[n].is_null = &i.session_null;
    n++;

    // access_time
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.access_time_value;
    b[n].is_null = &i.access_time_null;
    n++;

    // repositories_path
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.repositories_path_value.data ();
    b[n].size = &i.repositories_path_size;
    b[n].capacity = i.repositories_path_value.capacity ();
    b[n].is_null = &i.repositories_path_null;
    n++;

    // repositories_checksum
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.repositories_checksum_value.data ();
    b[n].size = &i.repositories_checksum_size;
    b[n].capacity = i.repositories_checksum_value.capacity ();
    b[n].is_null = &i.repositories_checksum_null;
    n++;

    // packages_path
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.packages_path_value.data ();
    b[n].size = &i.packages_path_size;
    b[n].capacity = i.packages_path_value.capacity ();
    b[n].is_null = &i.packages_path_null;
    n++;

    // packages_checksum
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.packages_checksum_value.data ();
    b[n].size = &i.packages_checksum_size;
    b[n].capacity = i.packages_checksum_value.capacity ();
    b[n].is_null = &i.packages_checksum_null;
    n++;
  }

  void access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::image_traits<
      ::bpkg::repository_url,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.id_value.data ();
    b[n].size = &i.id_size;
    b[n].capacity = i.id_value.capacity ();
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // url
    //
    if (sk == statement_insert)
    {
      ::bpkg::repository_url const& v =
        o.url;

      bool is_null (false);
      std::size_t cap (i.url_value.capacity ());
      sqlite::value_traits<
          ::bpkg::repository_url,
          sqlite::id_text >::set_image (
        i.url_value,
        i.url_size,
        is_null,
        v);
      i.url_null = is_null;
      grew = grew || (cap != i.url_value.capacity ());
    }

    // directory
    //
    {
      ::butl::dir_path const& v =
        o.directory;

      // From fetch-cache-data.hxx:62:14
      ::std::string const& vt =
        (v).string ();

      bool is_null (false);
      std::size_t cap (i.directory_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.directory_value,
        i.directory_size,
        is_null,
        vt);
      i.directory_null = is_null;
      grew = grew || (cap != i.directory_value.capacity ());
    }

    // session
    //
    {
      ::std::string const& v =
        o.session;

      bool is_null (false);
      std::size_t cap (i.session_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.session_value,
        i.session_size,
        is_null,
        v);
      i.session_null = is_null;
      grew = grew || (cap != i.session_value.capacity ());
    }

    // access_time
    //
    {
      ::butl::timestamp const& v =
        o.access_time;

      // From fetch-cache-data.hxx:47:14
      ::uint64_t const& vt =
        std::chrono::duration_cast < std::chrono::nanoseconds > ((v).time_since_epoch ()).count ();

      bool is_null (false);
      sqlite::value_traits<
          ::uint64_t,
          sqlite::id_integer >::set_image (
        i.access_time_value,
        is_null,
        vt);
      i.access_time_null = is_null;
    }

    // repositories_path
    //
    {
      ::butl::path const& v =
        o.repositories_path;

      // From fetch-cache-data.hxx:59:14
      ::std::string const& vt =
        (v).representation ();

      bool is_null (false);
      std::size_t cap (i.repositories_path_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.repositories_path_value,
        i.repositories_path_size,
        is_null,
        vt);
      i.repositories_path_null = is_null;
      grew = grew || (cap != i.repositories_path_value.capacity ());
    }

    // repositories_checksum
    //
    {
      ::std::string const& v =
        o.repositories_checksum;

      bool is_null (false);
      std::size_t cap (i.repositories_checksum_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.repositories_checksum_value,
        i.repositories_checksum_size,
        is_null,
        v);
      i.repositories_checksum_null = is_null;
      grew = grew || (cap != i.repositories_checksum_value.capacity ());
    }

    // packages_path
    //
    {
      ::butl::path const& v =
        o.packages_path;

      // From fetch-cache-data.hxx:59:14
      ::std::string const& vt =
        (v).representation ();

      bool is_null (false);
      std::size_t cap (i.packages_path_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.packages_path_value,
        i.packages_path_size,
        is_null,
        vt);
      i.packages_path_null = is_null;
      grew = grew || (cap != i.packages_path_value.capacity ());
    }

    // packages_checksum
    //
    {
      ::std::string const& v =
        o.packages_checksum;

      bool is_null (false);
      std::size_t cap (i.packages_checksum_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.packages_checksum_value,
        i.packages_checksum_size,
        is_null,
        v);
      i.packages_checksum_null = is_null;
      grew = grew || (cap != i.packages_checksum_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // url
    //
    {
      ::bpkg::repository_url& v =
        o.url;

      sqlite::value_traits<
          ::bpkg::repository_url,
          sqlite::id_text >::set_value (
        v,
        i.url_value,
        i.url_size,
        i.url_null);
    }

    // directory
    //
    {
      ::butl::dir_path& v =
        o.directory;

      ::std::string vt;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        vt,
        i.directory_value,
        i.directory_size,
        i.directory_null);

      // From fetch-cache-data.hxx:62:14
      v = bpkg::dir_path (vt);
    }

    // session
    //
    {
      ::std::string& v =
        o.session;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.session_value,
        i.session_size,
        i.session_null);
    }

    // access_time
    //
    {
      ::butl::timestamp& v =
        o.access_time;

      ::uint64_t vt;

      sqlite::value_traits<
          ::uint64_t,
          sqlite::id_integer >::set_value (
        vt,
        i.access_time_value,
        i.access_time_null);

      // From fetch-cache-data.hxx:47:14
      v = butl::timestamp (std::chrono::duration_cast < butl::timestamp::duration > (std::chrono::nanoseconds (vt)));
    }

    // repositories_path
    //
    {
      ::butl::path& v =
        o.repositories_path;

      ::std::string vt;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        vt,
        i.repositories_path_value,
        i.repositories_path_size,
        i.repositories_path_null);

      // From fetch-cache-data.hxx:59:14
      v = bpkg::path (vt);
    }

    // repositories_checksum
    //
    {
      ::std::string& v =
        o.repositories_checksum;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.repositories_checksum_value,
        i.repositories_checksum_size,
        i.repositories_checksum_null);
    }

    // packages_path
    //
    {
      ::butl::path& v =
        o.packages_path;

      ::std::string vt;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        vt,
        i.packages_path_value,
        i.packages_path_size,
        i.packages_path_null);

      // From fetch-cache-data.hxx:59:14
      v = bpkg::path (vt);
    }

    // packages_checksum
    //
    {
      ::std::string& v =
        o.packages_checksum;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.packages_checksum_value,
        i.packages_checksum_size,
        i.packages_checksum_null);
    }
  }

  void access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    bool grew (false);
    {
      bool is_null (false);
      std::size_t cap (i.id_value.capacity ());
      sqlite::value_traits<
          ::bpkg::repository_url,
          sqlite::id_text >::set_image (
        i.id_value,
        i.id_size,
        is_null,
        id);
      i.id_null = is_null;
      grew = grew || (cap != i.id_value.capacity ());
    }

    if (grew)
      i.version++;
  }

  const char access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::persist_statement[] =
  "INSERT INTO \"pkg_repository_metadata\" "
  "(\"url\", "
  "\"directory\", "
  "\"session\", "
  "\"access_time\", "
  "\"repositories_path\", "
  "\"repositories_checksum\", "
  "\"packages_path\", "
  "\"packages_checksum\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::find_statement[] =
  "SELECT "
  "\"pkg_repository_metadata\".\"url\", "
  "\"pkg_repository_metadata\".\"directory\", "
  "\"pkg_repository_metadata\".\"session\", "
  "\"pkg_repository_metadata\".\"access_time\", "
  "\"pkg_repository_metadata\".\"repositories_path\", "
  "\"pkg_repository_metadata\".\"repositories_checksum\", "
  "\"pkg_repository_metadata\".\"packages_path\", "
  "\"pkg_repository_metadata\".\"packages_checksum\" "
  "FROM \"pkg_repository_metadata\" "
  "WHERE \"pkg_repository_metadata\".\"url\"=?";

  const char access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::update_statement[] =
  "UPDATE \"pkg_repository_metadata\" "
  "SET "
  "\"directory\"=?, "
  "\"session\"=?, "
  "\"access_time\"=?, "
  "\"repositories_path\"=?, "
  "\"repositories_checksum\"=?, "
  "\"packages_path\"=?, "
  "\"packages_checksum\"=? "
  "WHERE \"url\"=?";

  const char access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::erase_statement[] =
  "DELETE FROM \"pkg_repository_metadata\" "
  "WHERE \"url\"=?";

  const char access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::query_statement[] =
  "SELECT "
  "\"pkg_repository_metadata\".\"url\", "
  "\"pkg_repository_metadata\".\"directory\", "
  "\"pkg_repository_metadata\".\"session\", "
  "\"pkg_repository_metadata\".\"access_time\", "
  "\"pkg_repository_metadata\".\"repositories_path\", "
  "\"pkg_repository_metadata\".\"repositories_checksum\", "
  "\"pkg_repository_metadata\".\"packages_path\", "
  "\"pkg_repository_metadata\".\"packages_checksum\" "
  "FROM \"pkg_repository_metadata\"";

  const char access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"pkg_repository_metadata\"";

  const char access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::table_name[] =
  "\"pkg_repository_metadata\"";

  void access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::pointer_type
  access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::object_type >
  access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  query (database& db, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"pkg_repository_metadata\"");
          db.execute ("CREATE TABLE IF NOT EXISTS \"schema_version\" (\n"
                      "  \"name\" TEXT NOT NULL PRIMARY KEY,\n"
                      "  \"version\" INTEGER NOT NULL,\n"
                      "  \"migration\" INTEGER NOT NULL)");
          db.execute ("DELETE FROM \"schema_version\"\n"
                      "  WHERE \"name\" = 'fetch-cache'");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"pkg_repository_metadata\" (\n"
                      "  \"url\" TEXT NULL PRIMARY KEY,\n"
                      "  \"directory\" TEXT NULL,\n"
                      "  \"session\" TEXT NULL,\n"
                      "  \"access_time\" INTEGER NULL,\n"
                      "  \"repositories_path\" TEXT NULL,\n"
                      "  \"repositories_checksum\" TEXT NULL,\n"
                      "  \"packages_path\" TEXT NULL,\n"
                      "  \"packages_checksum\" TEXT NULL)");
          db.execute ("CREATE UNIQUE INDEX \"pkg_repository_metadata_directory_i\"\n"
                      "  ON \"pkg_repository_metadata\" (\"directory\")");
          return true;
        }
        case 2:
        {
          db.execute ("CREATE TABLE IF NOT EXISTS \"schema_version\" (\n"
                      "  \"name\" TEXT NOT NULL PRIMARY KEY,\n"
                      "  \"version\" INTEGER NOT NULL,\n"
                      "  \"migration\" INTEGER NOT NULL)");
          db.execute ("INSERT OR IGNORE INTO \"schema_version\" (\n"
                      "  \"name\", \"version\", \"migration\")\n"
                      "  VALUES ('fetch-cache', 1, 0)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "fetch-cache",
    &create_schema);

  static const schema_catalog_migrate_entry
  migrate_schema_entry_1_ (
    id_sqlite,
    "fetch-cache",
    1ULL,
    0);
}

#include <odb/post.hxx>
