// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef BPKG_FETCH_CACHE_DATA_ODB_HXX
#define BPKG_FETCH_CACHE_DATA_ODB_HXX

// Begin prologue.
//
#include <bpkg/wrapper-traits.hxx>
#include <bpkg/value-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include <bpkg/fetch-cache-data.hxx>

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // pkg_repository_metadata
  //
  template <>
  struct class_traits< ::bpkg::pkg_repository_metadata >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::bpkg::pkg_repository_metadata >
  {
    public:
    typedef ::bpkg::pkg_repository_metadata object_type;
    typedef ::std::unique_ptr< ::bpkg::pkg_repository_metadata > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::bpkg::repository_url id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // pkg_repository_metadata
  //
  template <typename A>
  struct query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >
  {
    // url
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::bpkg::repository_url,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    url_type_;

    static const url_type_ url;

    // directory
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    directory_type_;

    static const directory_type_ directory;

    // session
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    session_type_;

    static const session_type_ session;

    // access_time
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint64_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    access_time_type_;

    static const access_time_type_ access_time;

    // repositories_path
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    repositories_path_type_;

    static const repositories_path_type_ repositories_path;

    // repositories_checksum
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    repositories_checksum_type_;

    static const repositories_checksum_type_ repositories_checksum;

    // packages_path
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    packages_path_type_;

    static const packages_path_type_ packages_path;

    // packages_checksum
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    packages_checksum_type_;

    static const packages_checksum_type_ packages_checksum;
  };

  template <typename A>
  const typename query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::url_type_
  query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::
  url (A::table_name, "\"url\"", 0);

  template <typename A>
  const typename query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::directory_type_
  query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::
  directory (A::table_name, "\"directory\"", 0);

  template <typename A>
  const typename query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::session_type_
  query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::
  session (A::table_name, "\"session\"", 0);

  template <typename A>
  const typename query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::access_time_type_
  query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::
  access_time (A::table_name, "\"access_time\"", 0);

  template <typename A>
  const typename query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::repositories_path_type_
  query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::
  repositories_path (A::table_name, "\"repositories_path\"", 0);

  template <typename A>
  const typename query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::repositories_checksum_type_
  query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::
  repositories_checksum (A::table_name, "\"repositories_checksum\"", 0);

  template <typename A>
  const typename query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::packages_path_type_
  query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::
  packages_path (A::table_name, "\"packages_path\"", 0);

  template <typename A>
  const typename query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::packages_checksum_type_
  query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >::
  packages_checksum (A::table_name, "\"packages_checksum\"", 0);

  template <typename A>
  struct pointer_query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >:
    query_columns< ::bpkg::pkg_repository_metadata, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >:
    public access::object_traits< ::bpkg::pkg_repository_metadata >
  {
    public:
    struct id_image_type
    {
      details::buffer id_value;
      std::size_t id_size;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // url
      //
      details::buffer url_value;
      std::size_t url_size;
      bool url_null;

      // directory
      //
      details::buffer directory_value;
      std::size_t directory_size;
      bool directory_null;

      // session
      //
      details::buffer session_value;
      std::size_t session_size;
      bool session_null;

      // access_time
      //
      long long access_time_value;
      bool access_time_null;

      // repositories_path
      //
      details::buffer repositories_path_value;
      std::size_t repositories_path_size;
      bool repositories_path_null;

      // repositories_checksum
      //
      details::buffer repositories_checksum_value;
      std::size_t repositories_checksum_size;
      bool repositories_checksum_null;

      // packages_path
      //
      details::buffer packages_path_value;
      std::size_t packages_path_size;
      bool packages_path_null;

      // packages_checksum
      //
      details::buffer packages_checksum_value;
      std::size_t packages_checksum_size;
      bool packages_checksum_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 8UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_common >:
    public access::object_traits_impl< ::bpkg::pkg_repository_metadata, id_sqlite >
  {
  };

  // pkg_repository_metadata
  //
}

#include <bpkg/fetch-cache-data-odb.ixx>

#include <odb/post.hxx>

#endif // BPKG_FETCH_CACHE_DATA_ODB_HXX
