// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

// Begin prologue.
//
//
// End prologue.

namespace bpkg
{
  // pkg_configure_options
  //
}

// Begin epilogue.
//
//
// End epilogue.
