// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

// Begin prologue.
//
//
// End prologue.

namespace bpkg
{
  // rep_fetch_options
  //

  inline const bool& rep_fetch_options::
  shallow () const
  {
    return this->shallow_;
  }
}

// Begin epilogue.
//
//
// End epilogue.
