# file      : tests/buildfile
# license   : MIT; see accompanying LICENSE file

define common: file
common{*}: extension = testscript

commons = common config auth remote \
          remote-git rep-fetch-git rep-fetch-git-refname rep-fetch-git-commit

# The common/ directory contains repositories that are reused, being symlinked
# in source repositories specific for testscripts.
#
./: testscript{* -{$commons}} common{$commons} {*/ -build/ -test/}{**} $bpkg
