# file      : tests/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

define common: file
common{*}: extension = test

commons = common config auth remote \
          remote-git rep-fetch-git rep-fetch-git-refname rep-fetch-git-commit

# The common/ directory contains repositories that are reused, being symlinked
# in source repositories specific for testscripts.
#
./: test{* -{$commons}} common{$commons} {*/ -build/ -test/}{**} $bpkg
