# file      : doc/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

cmds =             \
bpkg-cfg-create    \
bpkg-help          \
bpkg-pkg-build     \
bpkg-pkg-clean     \
bpkg-pkg-configure \
bpkg-pkg-disfigure \
bpkg-pkg-drop      \
bpkg-pkg-fetch     \
bpkg-pkg-install   \
bpkg-pkg-purge     \
bpkg-pkg-status    \
bpkg-pkg-test      \
bpkg-pkg-uninstall \
bpkg-pkg-unpack    \
bpkg-pkg-update    \
bpkg-pkg-verify    \
bpkg-rep-add 	   \
bpkg-rep-create    \
bpkg-rep-fetch     \
bpkg-rep-info

define css: file
css{*}: extension = css

define xhtml: doc
xhtml{*}: extension = xhtml

./: {man1 xhtml}{bpkg bpkg-common-options bpkg-repository-signing $cmds} \
    css{common pre-box man} 	                                         \
    file{man-prologue.1 man-epilogue.1                                   \
         man-prologue.xhtml man-epilogue.xhtml}

./: doc{build2-package-manager-manual.xhtml        \
        build2-package-manager-manual-a4.pdf       \
	build2-package-manager-manual-a4.ps        \
        build2-package-manager-manual-letter.pdf   \
	build2-package-manager-manual-letter.ps}   \
    css{code-box common doc pre-box toc} 	   \
    file{a4.html2ps letter.html2ps doc.html2ps}    \
    file{doc-prologue.xhtml doc-epilogue.xhtml     \
         manual.cli}

./: file{cli.sh}
