lib{hello}: {hxx cxx}{hello} hxx{export}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version.
#
if $version.pre_release
  lib{hello}: bin.lib.version = @"-$version.project_id"
else
  lib{hello}: bin.lib.version = @"-$version.major.$version.minor"

cxx.poptions += "-I$src_root"
obja{*}: cxx.poptions += -DLIBHELLO_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBHELLO_SHARED_BUILD

lib{hello}: cxx.export.poptions = "-I$src_root"
liba{hello}: cxx.export.poptions += -DLIBHELLO_STATIC
libs{hello}: cxx.export.poptions += -DLIBHELLO_SHARED

# Install into the libhello/ subdirectory of, say, /usr/include/.
#
{hxx ixx txx}{*}: install = include/libhello/
